env:
    browser: true
    jest: true
extends:
    - '@react-native-community'
    - airbnb
    - airbnb/hooks
    - plugin:react/recommended
    - eslint:recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/recommended-requiring-type-checking
    - prettier
    - plugin:prettier/recommended
    - plugin:import/warnings
    - plugin:import/typescript
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    project: './tsconfig.json'
plugins:
    - '@typescript-eslint'
    - prettier
    - react
    - import
    - jest
    - eslint-plugin-props-checker
rules:
    react/jsx-filename-extension:
        - error
        - extensions:
              - '.ts'
              - '.tsx'
    import/extensions:
        - error
        - ignorePackages
        - js: never
          jsx: never
          ts: never
          tsx: never
    linebreak-style: 0
    arrow-body-style:
        - warn
        - as-needed
    react/destructuring-assignment:
        - warn
        - always
        - ignoreClassFields: true
    react-hooks/exhaustive-deps: warn
    no-negated-condition: warn
    no-var: error
    no-plusplus: ['error', { 'allowForLoopAfterthoughts': true }]
    prefer-const: warn
    jsx-a11y/label-has-associated-control: off
    react/button-has-type: off
    '@typescript-eslint/no-floating-promises': off
    'react/function-component-definition':
        [2, { namedComponents: 'arrow-function', unnamedComponents: 'arrow-function' }]
    react/sort-comp:
        - warn
        - order:
              - type-annotations
              - static-methods
              - lifecycle
              - everything-else
              - handling
              - rendering
          groups:
              rendering:
                  - /^render.+$/
                  - render
              handling:
                  - /^handle.+$/
                  - /^on.+$/
    import/no-useless-path-segments: warn
    import/named: warn
    import/order: warn
    no-console: warn
    no-unused-vars: 'off'
    no-shadow: 'off'
    no-use-before-define: 'off'
    import/prefer-default-export: off
    import/no-unresolved: off
    react/display-name: off
    react/prop-types: 0
    no-param-reassign: 0
    prettier/prettier:
        - warn
        - singleQuote: true
    react/jsx-props-no-spreading: 0
    react/require-default-props: 0
    import/no-extraneous-dependencies: off
    prefer-promise-reject-errors: off
    class-methods-use-this:
        - error
        - enforceForClassFields: false
    'react-native/no-unused-styles': 2
    'react-native/no-color-literals': 2
